export const SVG = {
  Verified: require('./verified.svg').default,
  CarActive: require('./CarActive.svg').default,
  ProfileActive: require('./ProfileActive.svg').default,
  ProfileInActive: require('./ProfileInActive.svg').default,
  CarInActive: require('./CarInActive.svg').default,
  BookingsActive: require('./BookingActive.svg').default,
  BookingsInActive: require('./BookingInActive.svg').default,
  HomeActive: require('./HomeActive.svg').default,
  HomeInActive: require('./HomeInActive.svg').default,
  PrimaryVerified: require('./PrimaryVerified.svg').default,
  Google: require('./Google.svg').default,
  Apple: require('./Apple.svg').default,
  Facebook: require('./Facebook.svg').default,
  UploadPrimary: require('./UploadPrimary.svg').default,
  LocationPrimary: require('./LocationPrimary.svg').default,
  UploadWhite: require('./UploadWhite.svg').default,
  DropDown: require('./DropDown.svg').default,
  PlusDocument: require('./PlusDocument.svg').default,
  SupportPrimary: require('./SupportPrimary.svg').default,
  ProgressPrimary: require('./ProgressPrimary.svg').default,
  BigCarPrimary: require('./BigCarPrimary.svg').default,
  Humberger: require('./Humberger.svg').default,
  NoAlertWhite: require('./NoAlertWhite.svg').default,
  NoAlertGray: require('./NoAlertGray.svg').default,
  BellPrimary: require('./BellPrimary.svg').default,
  LocationYellow: require('./LocationYellow.svg').default,
  Search: require('./Search.svg').default,
  PlusPrimary: require('./PlusPrimary.svg').default,
  PendingYellow: require('./PendingYellow.svg').default,
  ClockGray: require('./ClockGray.svg').default,
  CalenderGray: require('./CalenderGray.svg').default,
  DollarGray: require('./DollarGray.svg').default,
  RightDashArrowGray: require('./RightDashArrowGray.svg').default,
  QuestionPrimary: require('./QuestionPrimary.svg').default,
  QuestionRed: require('./QuestionRed.svg').default,
  TickPrimary: require('./TickPrimary.svg').default,
  ChatPrimary: require('./ChatPrimary.svg').default,
  ConfirmGray: require('./ConfirmGray.svg').default,
  PlayPrimary: require('./PlayPrimary.svg').default,
  CamerPrimary: require('./CamerPrimary.svg').default,
  VideoPrimary: require('./VideoPrimary.svg').default,
  CrossPrimary: require('./CrossPrimary.svg').default,
  CompletedPrimary: require('./CompletedPrimary.svg').default,
  StarYellow: require('./StarYellow.svg').default,
  StarGray: require('./StarGray.svg').default,
  Block: require('./Block.svg').default,
  LocationGray: require('./LocationGray.svg').default,
  SearchingPrimary: require('./SearchingPrimary.svg').default,
  IDyellow: require('./IDyellow.svg').default,
  RequestSentPrimary: require('./RequestSentPrimary.svg').default,
  Decilned: require('./Decilned.svg').default,
  BellWithRedDot: require('./BellWithRedDot.svg').default,
  ChatWithYellowDot: require('./ChatWithYellowDot.svg').default,
  BellWhite: require('./BellWhite.svg').default,
  ChatWhite: require('./ChatWhite.svg').default,
  AcceptedYellow: require('./AcceptedYellow.svg').default,
  DownloadAppStore: require('./DownloadAppStore.svg').default,
  DownloadPlayStore: require('./DownloadPlayStore.svg').default,
  EditPrimary: require('./EditPrimary.svg').default,
  TrashYellow: require('./TrashYellow.svg').default,
  YellowDollar: require('./YellowDollar.svg').default,
  LogoutPrimary: require('./LogoutPrimary.svg').default,
  EyeOpen: require('./EyeOpen.svg').default,
  EyeClose: require('./EyeClose.svg').default,
  Warning: require('./Warning.svg').default,

  // drawer icons
  PrivacyGray: require('./PrivacyGray.svg').default,
  TermsConditon: require('./TermsConditon.svg').default,
  FaqGray: require('./FaqGray.svg').default,
  SettingGray: require('./SettingGray.svg').default,
  SupportGray: require('./SupportGray.svg').default,
  InviteGray: require('./InviteGray.svg').default,
  PayoutGray: require('./PayoutGray.svg').default,

  // payment icons
  MobilePay: require('./MobilePay.svg').default,
  StripeLogo: require('./StripeLogo.svg').default,

  // settings screen icons
  NotificationGray: require('./NotificationGray.svg').default,
  LanguageGray: require('./LanguageGray.svg').default,
  LockGray: require('./LockGray.svg').default,
  DeleteGray: require('./DeleteGray.svg').default,

  // invie and reward screen
  CopyPrimary: require('./CopyPrimary.svg').default,
  FacebookWithBg: require('./FacebookWithBg.svg').default,
  WhatsApp: require('./WhatsApp.svg').default,
  Instagram: require('./Instagram.svg').default,
  LinkedIn: require('./LinkedIn.svg').default,
  Tiktok: require('./Tiktok.svg').default,
  SadPrimary: require('./SadPrimary.svg').default,
  BackArrow: require('./BackArrow.svg').default,
  DownArrow: require('./DownArrow.svg').default,
  Document: require('./Document.svg').default,
};

export const SVG_PATH = {
  ProfileActive: 'ProfileActive',
  ProfileInActive: 'ProfileInActive',
  CarActive: 'CarActive',
  CarInActive: 'CarInActive',
  BookingsActive: 'BookingActive',
  BookingsInActive: 'BookingInActive',
  HomeActive: 'HomeActive',
  HomeInActive: 'HomeInActive',
  Verified: 'Verified',
  PrimaryVerified: 'PrimaryVerified',
  Google: 'Google',
  Apple: 'Apple',
  Facebook: 'Facebook',
  UploadPrimary: 'UploadPrimary',
  LocationPrimary: 'LocationPrimary',
  UploadWhite: 'UploadWhite',
  DropDown: 'DropDown',
  PlusDocument: 'PlusDocument',
  SupportPrimary: 'SupportPrimary',
  ProgressPrimary: 'ProgressPrimary',
  BigCarPrimary: 'BigCarPrimary',
  Humberger: 'Humberger',
  NoAlertWhite: 'NoAlertWhite',
  NoAlertGray: 'NoAlertGray',
  BellPrimary: 'BellPrimary',
  LocationYellow: 'LocationYellow',
  Search: 'Search',
  PlusPrimary: 'PlusPrimary',
  PendingYellow: 'PendingYellow',
  ClockGray: 'ClockGray',
  CalenderGray: 'CalenderGray',
  DollarGray: 'DollarGray',
  RightDashArrowGray: 'RightDashArrowGray',
  QuestionPrimary: 'QuestionPrimary',
  QuestionRed: 'QuestionRed',
  TickPrimary: 'TickPrimary',
  ChatPrimary: 'ChatPrimary',
  ConfirmGray: 'ConfirmGray',
  PlayPrimary: 'PlayPrimary',
  CamerPrimary: 'CamerPrimary',
  VideoPrimary: 'VideoPrimary',
  CrossPrimary: 'CrossPrimary',
  CompletedPrimary: 'CompletedPrimary',
  StarYellow: 'StarYellow',
  StarGray: 'StarGray',
  Block: 'Block',
  LocationGray: 'LocationGray',
  SearchingPrimary: 'SearchingPrimary',
  IDyellow: 'IDyellow',
  RequestSentPrimary: 'RequestSentPrimary',
  Decilned: 'Decilned',
  BellWithRedDot: 'BellWithRedDot',
  ChatWithYellowDot: 'ChatWithYellowDot',
  BellWhite: 'BellWhite',
  ChatWhite: 'ChatWhite',
  AcceptedYellow: 'AcceptedYellow',
  DownloadAppStore: 'DownloadAppStore',
  DownloadPlayStore: 'DownloadPlayStore',
  EditPrimary: 'EditPrimary',
  TrashYellow: 'TrashYellow',
  YellowDollar: 'YellowDollar',
  LogoutPrimary: 'LogoutPrimary',
  EyeOpen: 'EyeOpen',
  EyeClose: 'EyeClose',
  Warning: 'Warning',

  // drawer icons
  PrivacyGray: 'PrivacyGray',
  TermsConditon: 'TermsConditon',
  FaqGray: 'FaqGray',
  SettingGray: 'SettingGray',
  SupportGray: 'SupportGray',
  InviteGray: 'InviteGray',
  PayoutGray: 'PayoutGray',

  // payment icons
  StripeLogo: 'StripeLogo',
  MobilePay: 'MobilePay',

  // notification
  NotificationGray: 'NotificationGray',
  LanguageGray: 'LanguageGray',
  LockGray: 'LockGray',
  DeleteGray: 'DeleteGray',

  // invite and reward screen
  CopyPrimary: 'CopyPrimary',
  FacebookWithBg: 'FacebookWithBg',
  WhatsApp: 'WhatsApp',
  Instagram: 'Instagram',
  LinkedIn: 'LinkedIn',
  Tiktok: 'Tiktok',

  // sad primary
  SadPrimary: 'SadPrimary',

  // back arrow
  BackArrow: 'BackArrow',
  DownArrow: 'DownArrow',
  Document: 'Document',
};
