import { AccountSetScreen, HomeScreen, LibraryScreen,UploadingScreen } from '@/screens';
import { SVG } from '@/theme/assets/icons';
import i18next from 'i18next';
import { CountryCode } from 'libphonenumber-js';




export const ASYNC_TOKEN_KEY = 'USER_TOKEN';
export const ASYNC_USER_DATA_KEY = 'USER_DATA';
export const USER_LANGUAGE = 'USER_LANGUAGE';
export const FALL_BACK_LANG = 'en-US';


export interface CountryCodeData {
  name: string;
  code: CountryCode;
  dialCode: string;
  flag: string;
}


export const BOTTOM_TABS = [
  {
    name: 'HomeScreen',
    component: HomeScreen,
    svg: SVG.HomeActive,
    initialParams: {},
    title: 'Home',
  },
  {
    name: 'LibraryScreen',
    component: LibraryScreen,
    svg: SVG.Library,
    initialParams: {},
    title: 'Library',
  },
  {
    name: 'UploadingScreen',
    component: UploadingScreen,
    svg: SVG.Upload,
    initialParams: {},
    title: 'Upload',
  },
  {
    name: 'AccountSetScreen',
    component: AccountSetScreen,
    svg: SVG.ProfileActive,
    initialParams: {},
    title: 'Profile',
  },

];

// Sample subset of country codes with emoji flags
export const countryCodes: CountryCodeData[] = [
  {
    name: 'Afghanistan',
    dialCode: '93',
    flag: '🇦🇫',
    code: 'AF' as CountryCode,
  },
  {
    name: 'Aland Islands',
    dialCode: '358',
    flag: '🇦🇽',
    code: 'AX' as CountryCode,
  },
  {
    name: 'Albania',
    dialCode: '355',
    flag: '🇦🇱',
    code: 'AL',
  },
  {
    name: 'Algeria',
    dialCode: '213',
    flag: '🇩🇿',
    code: 'DZ',
  },
  {
    name: 'AmericanSamoa',
    dialCode: '1684',
    flag: '🇦🇸',
    code: 'AS',
  },
  {
    name: 'Andorra',
    dialCode: '376',
    flag: '🇦🇩',
    code: 'AD',
  },
  {
    name: 'Angola',
    dialCode: '244',
    flag: '🇦🇴',
    code: 'AO',
  },
  {
    name: 'Anguilla',
    dialCode: '1264',
    flag: '🇦🇮',
    code: 'AI',
  },
  {
    name: 'Antarctica',
    dialCode: '672',
    flag: '🇦🇶',
    code: 'AQ' as CountryCode,
  },
  {
    name: 'Antigua and Barbuda',
    dialCode: '1268',
    flag: '🇦🇬',
    code: 'AG' as CountryCode,
  },
  {
    name: 'Argentina',
    dialCode: '54',
    flag: '🇦🇷',
    code: 'AR' as CountryCode,
  },
  {
    name: 'Armenia',
    dialCode: '374',
    flag: '🇦🇲',
    code: 'AM' as CountryCode,
  },
  {
    name: 'Aruba',
    dialCode: '297',
    flag: '🇦🇼',
    code: 'AW' as CountryCode,
  },
  {
    name: 'Australia',
    dialCode: '61',
    flag: '🇦🇺',
    code: 'AU' as CountryCode,
  },
  {
    name: 'Austria',
    dialCode: '43',
    flag: '🇦🇹',
    code: 'AT' as CountryCode,
  },
  {
    name: 'Azerbaijan',
    dialCode: '994',
    flag: '🇦🇿',
    code: 'AZ' as CountryCode,
  },
  {
    name: 'Bahamas',
    dialCode: '1242',
    flag: '🇧🇸',
    code: 'BS' as CountryCode,
  },
  {
    name: 'Bahrain',
    dialCode: '973',
    flag: '🇧🇭',
    code: 'BH' as CountryCode,
  },
  {
    name: 'Bangladesh',
    dialCode: '880',
    flag: '🇧🇩',
    code: 'BD' as CountryCode,
  },
  {
    name: 'Barbados',
    dialCode: '1246',
    flag: '🇧🇧',
    code: 'BB' as CountryCode,
  },
  {
    name: 'Belarus',
    dialCode: '375',
    flag: '🇧🇾',
    code: 'BY' as CountryCode,
  },
  {
    name: 'Belgium',
    dialCode: '32',
    flag: '🇧🇪',
    code: 'BE' as CountryCode,
  },
  {
    name: 'Belize',
    dialCode: '501',
    flag: '🇧🇿',
    code: 'BZ' as CountryCode,
  },
  {
    name: 'Benin',
    dialCode: '229',
    flag: '🇧🇯',
    code: 'BJ' as CountryCode,
  },
  {
    name: 'Bermuda',
    dialCode: '1441',
    flag: '🇧🇲',
    code: 'BM' as CountryCode,
  },
  {
    name: 'Bhutan',
    dialCode: '975',
    flag: '🇧🇹',
    code: 'BT' as CountryCode,
  },
  {
    name: 'Bolivia, Plurinational State of',
    dialCode: '591',
    flag: '🇧🇴',
    code: 'BO' as CountryCode,
  },
  {
    name: 'Bosnia and Herzegovina',
    dialCode: '387',
    flag: '🇧🇦',
    code: 'BA' as CountryCode,
  },
  {
    name: 'Botswana',
    dialCode: '267',
    flag: '🇧🇼',
    code: 'BW' as CountryCode,
  },
  {
    name: 'Brazil',
    dialCode: '55',
    flag: '🇧🇷',
    code: 'BR' as CountryCode,
  },
  {
    name: 'British Indian Ocean Territory',
    dialCode: '246',
    flag: '🇮🇴',
    code: 'IO' as CountryCode,
  },
  {
    name: 'Brunei Darussalam',
    dialCode: '673',
    flag: '🇧🇳',
    code: 'BN' as CountryCode,
  },
  {
    name: 'Bulgaria',
    dialCode: '359',
    flag: '🇧🇬',
    code: 'BG' as CountryCode,
  },
  {
    name: 'Burkina Faso',
    dialCode: '226',
    flag: '🇧🇫',
    code: 'BF' as CountryCode,
  },
  {
    name: 'Burundi',
    dialCode: '257',
    flag: '🇧🇮',
    code: 'BI' as CountryCode,
  },
  {
    name: 'Cambodia',
    dialCode: '855',
    flag: '🇰🇭',
    code: 'KH' as CountryCode,
  },
  {
    name: 'Cameroon',
    dialCode: '237',
    flag: '🇨🇲',
    code: 'CM' as CountryCode,
  },
  {
    name: 'Canada',
    dialCode: '1',
    flag: '🇨🇦',
    code: 'CA' as CountryCode,
  },
  {
    name: 'Cape Verde',
    dialCode: '238',
    flag: '🇨🇻',
    code: 'CV' as CountryCode,
  },
  {
    name: 'Cayman Islands',
    dialCode: '345',
    flag: '🇰🇾',
    code: 'KY' as CountryCode,
  },
  {
    name: 'Central African Republic',
    dialCode: '236',
    flag: '🇨🇫',
    code: 'CF' as CountryCode,
  },
  {
    name: 'Chad',
    dialCode: '235',
    flag: '🇹🇩',
    code: 'TD' as CountryCode,
  },
  {
    name: 'Chile',
    dialCode: '56',
    flag: '🇨🇱',
    code: 'CL' as CountryCode,
  },
  {
    name: 'China',
    dialCode: '86',
    flag: '🇨🇳',
    code: 'CN' as CountryCode,
  },
  {
    name: 'Christmas Island',
    dialCode: '61',
    flag: '🇨🇽',
    code: 'CX' as CountryCode,
  },
  {
    name: 'Cocos (Keeling) Islands',
    dialCode: '61',
    flag: '🇨🇨',
    code: 'CC' as CountryCode,
  },
  {
    name: 'Colombia',
    dialCode: '57',
    flag: '🇨🇴',
    code: 'CO' as CountryCode,
  },
  {
    name: 'Comoros',
    dialCode: '269',
    flag: '🇰🇲',
    code: 'KM' as CountryCode,
  },
  {
    name: 'Congo',
    dialCode: '242',
    flag: '🇨🇬',
    code: 'CG' as CountryCode,
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    dialCode: '243',
    flag: '🇨🇩',
    code: 'CD' as CountryCode,
  },
  {
    name: 'Cook Islands',
    dialCode: '682',
    flag: '🇨🇰',
    code: 'CK' as CountryCode,
  },
  {
    name: 'Costa Rica',
    dialCode: '506',
    flag: '🇨🇷',
    code: 'CR' as CountryCode,
  },
  {
    name: "Cote d'Ivoire",
    dialCode: '225',
    flag: '🇨🇮',
    code: 'CI' as CountryCode,
  },
  {
    name: 'Croatia',
    dialCode: '385',
    flag: '🇭🇷',
    code: 'HR' as CountryCode,
  },
  {
    name: 'Cuba',
    dialCode: '53',
    flag: '🇨🇺',
    code: 'CU' as CountryCode,
  },
  {
    name: 'Cyprus',
    dialCode: '357',
    flag: '🇨🇾',
    code: 'CY' as CountryCode,
  },
  {
    name: 'Czech Republic',
    dialCode: '420',
    flag: '🇨🇿',
    code: 'CZ' as CountryCode,
  },
  {
    name: 'Denmark',
    dialCode: '45',
    flag: '🇩🇰',
    code: 'DK' as CountryCode,
  },
  {
    name: 'Djibouti',
    dialCode: '253',
    flag: '🇩🇯',
    code: 'DJ' as CountryCode,
  },
  {
    name: 'Dominica',
    dialCode: '1767',
    flag: '🇩🇲',
    code: 'DM' as CountryCode,
  },
  {
    name: 'Dominican Republic',
    dialCode: '1849',
    flag: '🇩🇴',
    code: 'DO' as CountryCode,
  },
  {
    name: 'Ecuador',
    dialCode: '593',
    flag: '🇪🇨',
    code: 'EC' as CountryCode,
  },
  {
    name: 'Egypt',
    dialCode: '20',
    flag: '🇪🇬',
    code: 'EG' as CountryCode,
  },
  {
    name: 'El Salvador',
    dialCode: '503',
    flag: '🇸🇻',
    code: 'SV' as CountryCode,
  },
  {
    name: 'Equatorial Guinea',
    dialCode: '240',
    flag: '🇬🇶',
    code: 'GQ' as CountryCode,
  },
  {
    name: 'Eritrea',
    dialCode: '291',
    flag: '🇪🇷',
    code: 'ER' as CountryCode,
  },
  {
    name: 'Estonia',
    dialCode: '372',
    flag: '🇪🇪',
    code: 'EE' as CountryCode,
  },
  {
    name: 'Ethiopia',
    dialCode: '251',
    flag: '🇪🇹',
    code: 'ET' as CountryCode,
  },
  {
    name: 'Falkland Islands (Malvinas)',
    dialCode: '500',
    flag: '🇫🇰',
    code: 'FK' as CountryCode,
  },
  {
    name: 'Faroe Islands',
    dialCode: '298',
    flag: '🇫🇴',
    code: 'FO' as CountryCode,
  },
  {
    name: 'Fiji',
    dialCode: '679',
    flag: '🇫🇯',
    code: 'FJ' as CountryCode,
  },
  {
    name: 'Finland',
    dialCode: '358',
    flag: '🇫🇮',
    code: 'FI' as CountryCode,
  },
  {
    name: 'France',
    dialCode: '33',
    flag: '🇫🇷',
    code: 'FR' as CountryCode,
  },
  {
    name: 'French Guiana',
    dialCode: '594',
    flag: '🇬🇫',
    code: 'GF' as CountryCode,
  },
  {
    name: 'French Polynesia',
    dialCode: '689',
    flag: '🇵🇫',
    code: 'PF' as CountryCode,
  },
  {
    name: 'Gabon',
    dialCode: '241',
    flag: '🇬🇦',
    code: 'GA' as CountryCode,
  },
  {
    name: 'Gambia',
    dialCode: '220',
    flag: '🇬🇲',
    code: 'GM' as CountryCode,
  },
  {
    name: 'Georgia',
    dialCode: '995',
    flag: '🇬🇪',
    code: 'GE' as CountryCode,
  },
  {
    name: 'Germany',
    dialCode: '49',
    flag: '🇩🇪',
    code: 'DE' as CountryCode,
  },
  {
    name: 'Ghana',
    dialCode: '233',
    flag: '🇬🇭',
    code: 'GH' as CountryCode,
  },
  {
    name: 'Gibraltar',
    dialCode: '350',
    flag: '🇬🇮',
    code: 'GI' as CountryCode,
  },
  {
    name: 'Greece',
    dialCode: '30',
    flag: '🇬🇷',
    code: 'GR' as CountryCode,
  },
  {
    name: 'Greenland',
    dialCode: '299',
    flag: '🇬🇱',
    code: 'GL' as CountryCode,
  },
  {
    name: 'Grenada',
    dialCode: '1473',
    flag: '🇬🇩',
    code: 'GD' as CountryCode,
  },
  {
    name: 'Guadeloupe',
    dialCode: '590',
    flag: '🇬🇵',
    code: 'GP' as CountryCode,
  },
  {
    name: 'Guam',
    dialCode: '1671',
    flag: '🇬🇺',
    code: 'GU' as CountryCode,
  },
  {
    name: 'Guatemala',
    dialCode: '502',
    flag: '🇬🇹',
    code: 'GT' as CountryCode,
  },
  {
    name: 'Guernsey',
    dialCode: '44',
    flag: '🇬🇬',
    code: 'GG' as CountryCode,
  },
  {
    name: 'Guinea',
    dialCode: '224',
    flag: '🇬🇳',
    code: 'GN' as CountryCode,
  },
  {
    name: 'Guinea-Bissau',
    dialCode: '245',
    flag: '🇬🇼',
    code: 'GW' as CountryCode,
  },
  {
    name: 'Guyana',
    dialCode: '595',
    flag: '🇬🇾',
    code: 'GY' as CountryCode,
  },
  {
    name: 'Haiti',
    dialCode: '509',
    flag: '🇭🇹',
    code: 'HT' as CountryCode,
  },
  {
    name: 'Holy See (Vatican City State)',
    dialCode: '379',
    flag: '🇻🇦',
    code: 'VA' as CountryCode,
  },
  {
    name: 'Honduras',
    dialCode: '504',
    flag: '🇭🇳',
    code: 'HN' as CountryCode,
  },
  {
    name: 'Hong Kong',
    dialCode: '852',
    flag: '🇭🇰',
    code: 'HK' as CountryCode,
  },
  {
    name: 'Hungary',
    dialCode: '36',
    flag: '🇭🇺',
    code: 'HU' as CountryCode,
  },
  {
    name: 'Iceland',
    dialCode: '354',
    flag: '🇮🇸',
    code: 'IS' as CountryCode,
  },
  {
    name: 'India',
    dialCode: '91',
    flag: '🇮🇳',
    code: 'IN' as CountryCode,
  },
  {
    name: 'Indonesia',
    dialCode: '62',
    flag: '🇮🇩',
    code: 'ID' as CountryCode,
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    dialCode: '98',
    flag: '🇮🇷',
    code: 'IR' as CountryCode,
  },
  {
    name: 'Iraq',
    dialCode: '964',
    flag: '🇮🇷',
    code: 'IQ' as CountryCode,
  },
  {
    name: 'Ireland',
    dialCode: '353',
    flag: '🇮🇪',
    code: 'IE' as CountryCode,
  },
  {
    name: 'Isle of Man',
    dialCode: '44',
    flag: '🇮🇲',
    code: 'IM' as CountryCode,
  },
  {
    name: 'Israel',
    dialCode: '972',
    flag: '🇮🇱',
    code: 'IL' as CountryCode,
  },
  {
    name: 'Italy',
    dialCode: '39',
    flag: '🇮🇹',
    code: 'IT' as CountryCode,
  },
  {
    name: 'Jamaica',
    dialCode: '1876',
    flag: '🇯🇲',
    code: 'JM' as CountryCode,
  },
  {
    name: 'Japan',
    dialCode: '81',
    flag: '🇯🇵',
    code: 'JP' as CountryCode,
  },
  {
    name: 'Jersey',
    dialCode: '44',
    flag: '🇯🇪',
    code: 'JE' as CountryCode,
  },
  {
    name: 'Jordan',
    dialCode: '962',
    flag: '🇯🇴',
    code: 'JO' as CountryCode,
  },
  {
    name: 'Kazakhstan',
    dialCode: '77',
    flag: '🇰🇿',
    code: 'KZ' as CountryCode,
  },
  {
    name: 'Kenya',
    dialCode: '254',
    flag: '🇰🇪',
    code: 'KE' as CountryCode,
  },
  {
    name: 'Kiribati',
    dialCode: '686',
    flag: '🇰🇮',
    code: 'KI' as CountryCode,
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dialCode: '850',
    flag: '🇰🇵',
    code: 'KP' as CountryCode,
  },
  {
    name: 'Korea, Republic of South Korea',
    dialCode: '82',
    flag: '🇰🇷',
    code: 'KR' as CountryCode,
  },
  {
    name: 'Kuwait',
    dialCode: '965',
    flag: '🇰🇼',
    code: 'KW' as CountryCode,
  },
  {
    name: 'Kyrgyzstan',
    dialCode: '996',
    flag: '🇰🇬',
    code: 'KG' as CountryCode,
  },
  {
    name: 'Laos',
    dialCode: '856',
    flag: '🇱🇦',
    code: 'LA' as CountryCode,
  },
  {
    name: 'Latvia',
    dialCode: '371',
    flag: '🇱🇻',
    code: 'LV' as CountryCode,
  },
  {
    name: 'Lebanon',
    dialCode: '961',
    flag: '🇱🇧',
    code: 'LB' as CountryCode,
  },
  {
    name: 'Lesotho',
    dialCode: '266',
    flag: '🇱🇸',
    code: 'LS' as CountryCode,
  },
  {
    name: 'Liberia',
    dialCode: '231',
    flag: '🇱🇷',
    code: 'LR' as CountryCode,
  },
  {
    name: 'Libyan Arab Jamahiriya',
    dialCode: '218',
    flag: '🇱🇾',
    code: 'LY' as CountryCode,
  },
  {
    name: 'Liechtenstein',
    dialCode: '423',
    flag: '🇱🇮',
    code: 'LI' as CountryCode,
  },
  {
    name: 'Lithuania',
    dialCode: '370',
    flag: '🇱🇹',
    code: 'LT' as CountryCode,
  },
  {
    name: 'Luxembourg',
    dialCode: '352',
    flag: '🇱🇺',
    code: 'LU' as CountryCode,
  },
  {
    name: 'Macao',
    dialCode: '853',
    flag: '🇲🇴',
    code: 'MO' as CountryCode,
  },
  {
    name: 'Macedonia',
    dialCode: '389',
    flag: '🇲🇰',
    code: 'MK' as CountryCode,
  },
  {
    name: 'Madagascar',
    dialCode: '261',
    flag: '🇲🇬',
    code: 'MG' as CountryCode,
  },
  {
    name: 'Malawi',
    dialCode: '265',
    flag: '🇲🇼',
    code: 'MW' as CountryCode,
  },
  {
    name: 'Malaysia',
    dialCode: '60',
    flag: '🇲🇾',
    code: 'MY' as CountryCode,
  },
  {
    name: 'Maldives',
    dialCode: '960',
    flag: '🇲🇻',
    code: 'MV' as CountryCode,
  },
  {
    name: 'Mali',
    dialCode: '223',
    flag: '🇲🇱',
    code: 'ML' as CountryCode,
  },
  {
    name: 'Malta',
    dialCode: '356',
    flag: '🇲🇹',
    code: 'MT' as CountryCode,
  },
  {
    name: 'Marshall Islands',
    dialCode: '692',
    flag: '🇲🇭',
    code: 'MH' as CountryCode,
  },
  {
    name: 'Martinique',
    dialCode: '596',
    flag: '🇲🇶',
    code: 'MQ' as CountryCode,
  },
  {
    name: 'Mauritania',
    dialCode: '222',
    flag: '🇲🇷',
    code: 'MR' as CountryCode,
  },
  {
    name: 'Mauritius',
    dialCode: '230',
    flag: '🇲🇺',
    code: 'MU' as CountryCode,
  },
  {
    name: 'Mayotte',
    dialCode: '262',
    flag: '🇾🇹',
    code: 'YT' as CountryCode,
  },
  {
    name: 'Mexico',
    dialCode: '52',
    flag: '🇲🇽',
    code: 'MX' as CountryCode,
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    dialCode: '691',
    flag: '🇫🇲',
    code: 'FM' as CountryCode,
  },
  {
    name: 'Moldova',
    dialCode: '373',
    flag: '🇲🇩',
    code: 'MD' as CountryCode,
  },
  {
    name: 'Monaco',
    dialCode: '377',
    flag: '🇲🇨',
    code: 'MC' as CountryCode,
  },
  {
    name: 'Mongolia',
    dialCode: '976',
    flag: '🇲🇳',
    code: 'MN' as CountryCode,
  },
  {
    name: 'Montenegro',
    dialCode: '382',
    flag: '🇲🇪',
    code: 'ME' as CountryCode,
  },
  {
    name: 'Montserrat',
    dialCode: '1664',
    flag: '🇲🇸',
    code: 'MS' as CountryCode,
  },
  {
    name: 'Morocco',
    dialCode: '212',
    flag: '🇲🇦',
    code: 'MA' as CountryCode,
  },
  {
    name: 'Mozambique',
    dialCode: '258',
    flag: '🇲🇿',
    code: 'MZ' as CountryCode,
  },
  {
    name: 'Myanmar',
    dialCode: '95',
    flag: '🇲🇲',
    code: 'MM' as CountryCode,
  },
  {
    name: 'Namibia',
    flag: '🇳🇦',
    dialCode: '264',
    code: 'NA' as CountryCode,
  },
  {
    name: 'Nauru',
    dialCode: '674',
    flag: '🇳🇷',
    code: 'NR' as CountryCode,
  },
  {
    name: 'Nepal',
    dialCode: '977',
    flag: '🇳🇵',
    code: 'NP' as CountryCode,
  },
  {
    name: 'Netherlands',
    dialCode: '31',
    flag: '🇳🇱',
    code: 'NL' as CountryCode,
  },
  {
    name: 'Netherlands Antilles',
    dialCode: '599',
    flag: '🇧🇶',
    code: 'AN' as CountryCode,
  },
  {
    name: 'New Caledonia',
    dialCode: '687',
    flag: '🇳🇨',
    code: 'NC' as CountryCode,
  },
  {
    name: 'New Zealand',
    dialCode: '64',
    flag: '🇳🇿',
    code: 'NZ' as CountryCode,
  },
  {
    name: 'Nicaragua',
    dialCode: '505',
    flag: '🇳🇮',
    code: 'NI' as CountryCode,
  },
  {
    name: 'Niger',
    dialCode: '227',
    flag: '🇳🇪',
    code: 'NE' as CountryCode,
  },
  {
    name: 'Nigeria',
    dialCode: '234',
    flag: '🇳🇬',
    code: 'NG' as CountryCode,
  },
  {
    name: 'Niue',
    dialCode: '683',
    flag: '🇳🇺',
    code: 'NU' as CountryCode,
  },
  {
    name: 'Norfolk Island',
    dialCode: '672',
    flag: '🇳🇫',
    code: 'NF' as CountryCode,
  },
  {
    name: 'Northern Mariana Islands',
    dialCode: '1670',
    flag: '🇲🇵',
    code: 'MP' as CountryCode,
  },
  {
    name: 'Norway',
    dialCode: '47',
    flag: '🇳🇴',
    code: 'NO' as CountryCode,
  },
  {
    name: 'Oman',
    dialCode: '968',
    flag: '🇴🇲',
    code: 'OM' as CountryCode,
  },
  {
    name: 'Pakistan',
    dialCode: '92',
    flag: '🇵🇰',
    code: 'PK' as CountryCode,
  },
  {
    name: 'Palau',
    dialCode: '680',
    flag: '🇵🇼',
    code: 'PW' as CountryCode,
  },
  {
    name: 'Palestinian Territory, Occupied',
    dialCode: '970',
    flag: '🇵🇸',
    code: 'PS' as CountryCode,
  },
  {
    name: 'Panama',
    dialCode: '507',
    flag: '🇵🇦',
    code: 'PA' as CountryCode,
  },
  {
    name: 'Papua New Guinea',
    dialCode: '675',
    flag: '🇵🇬',
    code: 'PG' as CountryCode,
  },
  {
    name: 'Paraguay',
    dialCode: '595',
    flag: '🇵🇾',
    code: 'PY' as CountryCode,
  },
  {
    name: 'Peru',
    dialCode: '51',
    flag: '🇵🇪',
    code: 'PE' as CountryCode,
  },
  {
    name: 'Philippines',
    dialCode: '63',
    flag: '🇵🇭',
    code: 'PH' as CountryCode,
  },
  {
    name: 'Pitcairn',
    dialCode: '872',
    flag: '🇵🇳',
    code: 'PN' as CountryCode,
  },
  {
    name: 'Poland',
    dialCode: '48',
    flag: '🇵🇱',
    code: 'PL' as CountryCode,
  },
  {
    name: 'Portugal',
    dialCode: '351',
    flag: '🇵🇹',
    code: 'PT' as CountryCode,
  },
  {
    name: 'Puerto Rico',
    dialCode: '1939',
    flag: '🇵🇷',
    code: 'PR' as CountryCode,
  },
  {
    name: 'Qatar',
    dialCode: '974',
    flag: '🇶🇦',
    code: 'QA' as CountryCode,
  },
  {
    name: 'Romania',
    dialCode: '40',
    flag: '🇷🇴',
    code: 'RO' as CountryCode,
  },
  {
    name: 'Russia',
    dialCode: '7',
    flag: '🇷🇺',
    code: 'RU' as CountryCode,
  },
  {
    name: 'Rwanda',
    dialCode: '250',
    flag: '🇷🇼',
    code: 'RW' as CountryCode,
  },
  {
    name: 'Reunion',
    dialCode: '262',
    flag: '🇷🇪',
    code: 'RE' as CountryCode,
  },
  {
    name: 'Saint Barthelemy',
    dialCode: '590',
    flag: '🇧🇱',
    code: 'BL' as CountryCode,
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dialCode: '290',
    flag: '🇸🇭',
    code: 'SH' as CountryCode,
  },
  {
    name: 'Saint Kitts and Nevis',
    dialCode: '1869',
    flag: '🇰🇳',
    code: 'KN' as CountryCode,
  },
  {
    name: 'Saint Lucia',
    dialCode: '1758',
    flag: '🇱🇨',
    code: 'LC' as CountryCode,
  },
  {
    name: 'Saint Martin',
    dialCode: '590',
    flag: '🇲🇫',
    code: 'MF' as CountryCode,
  },
  {
    name: 'Saint Pierre and Miquelon',
    dialCode: '508',
    flag: '🇵🇲',
    code: 'PM' as CountryCode,
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dialCode: '1784',
    flag: '🇻🇨',
    code: 'VC' as CountryCode,
  },
  {
    name: 'Samoa',
    dialCode: '685',
    flag: '🇼🇸',
    code: 'WS' as CountryCode,
  },
  {
    name: 'San Marino',
    dialCode: '378',
    flag: '🇸🇲',
    code: 'SM' as CountryCode,
  },
  {
    name: 'Sao Tome and Principe',
    dialCode: '239',
    flag: '🇸🇹',
    code: 'ST' as CountryCode,
  },
  {
    name: 'Saudi Arabia',
    dialCode: '966',
    flag: '🇸🇦',
    code: 'SA' as CountryCode,
  },
  {
    name: 'Senegal',
    dialCode: '221',
    flag: '🇸🇳',
    code: 'SN' as CountryCode,
  },
  {
    name: 'Serbia',
    dialCode: '381',
    flag: '🇷🇸',
    code: 'RS' as CountryCode,
  },
  {
    name: 'Seychelles',
    dialCode: '248',
    flag: '🇸🇨',
    code: 'SC' as CountryCode,
  },
  {
    name: 'Sierra Leone',
    dialCode: '232',
    flag: '🇸🇱',
    code: 'SL' as CountryCode,
  },
  {
    name: 'Singapore',
    dialCode: '65',
    flag: '🇸🇬',
    code: 'SG' as CountryCode,
  },
  {
    name: 'Slovakia',
    dialCode: '421',
    flag: '🇸🇰',
    code: 'SK' as CountryCode,
  },
  {
    name: 'Slovenia',
    dialCode: '386',
    flag: '🇸🇮',
    code: 'SI' as CountryCode,
  },
  {
    name: 'Solomon Islands',
    dialCode: '677',
    flag: '🇸🇧',
    code: 'SB' as CountryCode,
  },
  {
    name: 'Somalia',
    dialCode: '252',
    flag: '🇸🇴',
    code: 'SO' as CountryCode,
  },
  {
    name: 'South Africa',
    dialCode: '27',
    flag: '🇿🇦',
    code: 'ZA' as CountryCode,
  },
  {
    name: 'South Sudan',
    dialCode: '211',
    flag: '🇸🇸',
    code: 'SS' as CountryCode,
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dialCode: '500',
    flag: '🇬🇸',
    code: 'GS' as CountryCode,
  },
  {
    name: 'Spain',
    dialCode: '34',
    flag: '🇪🇸',
    code: 'ES' as CountryCode,
  },
  {
    name: 'Sri Lanka',
    dialCode: '94',
    flag: '🇱🇰',
    code: 'LK' as CountryCode,
  },
  {
    name: 'Sudan',
    dialCode: '249',
    flag: '🇸🇩',
    code: 'SD' as CountryCode,
  },
  {
    name: 'Suriname',
    dialCode: '597',
    flag: '🇸🇷',
    code: 'SR' as CountryCode,
  },
  {
    name: 'Svalbard and Jan Mayen',
    dialCode: '47',
    flag: '🇸🇯',
    code: 'SJ' as CountryCode,
  },
  {
    name: 'Swaziland',
    dialCode: '268',
    flag: '🇸🇿',
    code: 'SZ' as CountryCode,
  },
  {
    name: 'Sweden',
    dialCode: '46',
    flag: '🇸🇪',
    code: 'SE' as CountryCode,
  },
  {
    name: 'Switzerland',
    dialCode: '41',
    flag: '🇨🇭',
    code: 'CH' as CountryCode,
  },
  {
    name: 'Syrian Arab Republic',
    dialCode: '963',
    flag: '🇸🇾',
    code: 'SY' as CountryCode,
  },
  {
    name: 'Taiwan',
    dialCode: '886',
    flag: '🇹🇼',
    code: 'TW' as CountryCode,
  },
  {
    name: 'Tajikistan',
    dialCode: '992',
    flag: '🇹🇯',
    code: 'TJ' as CountryCode,
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    dialCode: '255',
    flag: '🇹🇿',
    code: 'TZ' as CountryCode,
  },
  {
    name: 'Thailand',
    dialCode: '66',
    flag: '🇹🇭',
    code: 'TH' as CountryCode,
  },
  {
    name: 'Timor-Leste',
    dialCode: '670',
    flag: '🇹🇱',
    code: 'TL' as CountryCode,
  },
  {
    name: 'Togo',
    dialCode: '228',
    flag: '🇹🇬',
    code: 'TG' as CountryCode,
  },
  {
    name: 'Tokelau',
    dialCode: '690',
    flag: '🇹🇰',
    code: 'TK' as CountryCode,
  },
  {
    name: 'Tonga',
    dialCode: '676',
    flag: '🇹🇴',
    code: 'TO' as CountryCode,
  },
  {
    name: 'Trinidad and Tobago',
    dialCode: '1868',
    flag: '🇹🇹',
    code: 'TT' as CountryCode,
  },
  {
    name: 'Tunisia',
    dialCode: '216',
    flag: '🇹🇳',
    code: 'TN' as CountryCode,
  },
  {
    name: 'Turkey',
    dialCode: '90',
    flag: '🇹🇷',
    code: 'TR' as CountryCode,
  },
  {
    name: 'Turkmenistan',
    dialCode: '993',
    flag: '🇹🇲',
    code: 'TM' as CountryCode,
  },
  {
    name: 'Turks and Caicos Islands',
    dialCode: '1649',
    flag: '🇹🇨',
    code: 'TC' as CountryCode,
  },
  {
    name: 'Tuvalu',
    dialCode: '688',
    flag: '🇹🇻',
    code: 'TV' as CountryCode,
  },
  {
    name: 'Uganda',
    dialCode: '256',
    flag: '🇺🇬',
    code: 'UG' as CountryCode,
  },
  {
    name: 'Ukraine',
    dialCode: '380',
    flag: '🇺🇦',
    code: 'UA' as CountryCode,
  },
  {
    name: 'United Arab Emirates',
    dialCode: '971',
    flag: '🇦🇪',
    code: 'AE' as CountryCode,
  },
  {
    name: 'United Kingdom',
    dialCode: '44',
    flag: '🇬🇧',
    code: 'GB' as CountryCode,
  },
  {
    name: 'United States',
    dialCode: '1',
    flag: '🇺🇸',
    code: 'US' as CountryCode,
  },
  {
    name: 'Uruguay',
    dialCode: '598',
    flag: '🇺🇾',
    code: 'UY' as CountryCode,
  },
  {
    name: 'Uzbekistan',
    dialCode: '998',
    flag: '🇺🇿',
    code: 'UZ' as CountryCode,
  },
  {
    name: 'Vanuatu',
    dialCode: '678',
    flag: '🇻🇺',
    code: 'VU' as CountryCode,
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    dialCode: '58',
    flag: '🇻🇪',
    code: 'VE' as CountryCode,
  },
  {
    name: 'Vietnam',
    dialCode: '84',
    flag: '🇻🇳',
    code: 'VN' as CountryCode,
  },
  {
    name: 'Virgin Islands, British',
    dialCode: '1284',
    flag: '🇻🇬',
    code: 'VG' as CountryCode,
  },
  {
    name: 'Virgin Islands, U.S.',
    dialCode: '1340',
    flag: '🇻🇮',
    code: 'VI' as CountryCode,
  },
  {
    name: 'Wallis and Futuna',
    dialCode: '681',
    flag: '🇼🇫',
    code: 'WF' as CountryCode,
  },
  {
    name: 'Yemen',
    dialCode: '967',
    flag: '🇾🇪',
    code: 'YE' as CountryCode,
  },
  {
    name: 'Zambia',
    dialCode: '260',
    flag: '🇿🇲',
    code: 'ZM' as CountryCode,
  },
  {
    name: 'Zimbabwe',
    dialCode: '263',
    flag: '🇿🇼',
    code: 'ZW' as CountryCode,
  },
];

export const ID_DROPDOWN = [
  {
    key: 'passport',
    value: i18next.t('screen_AdditionalInfo.passport'),
  },
  {
    key: 'idCard',
    value: i18next.t('screen_AdditionalInfo.identityCard'),
  },
];

export const UPLOAD_ID = [
  {
    key: 'front',
    title: i18next.t('screen_AdditionalInfo.uploadId'),
    subTitle: i18next.t('screen_AdditionalInfo.uploadFront'),
  },
  {
    key: 'back',
    subTitle: i18next.t('screen_AdditionalInfo.uploadBack'),
  },
];

export const UPLOAD_PASSPORT = [
  {
    key: 'passport',
    title: i18next.t('screen_AdditionalInfo.uploadPass'),
    subTitle: i18next.t('screen_AdditionalInfo.uploadPass'),
  },
];

export const DRIVING_LIC = [
  {
    key: 'front',
    subTitle: i18next.t('screen_AdditionalInfo.uploadFront'),
  },
  {
    key: 'back',
    subTitle: i18next.t('screen_AdditionalInfo.uploadBack'),
  },
];
