export const enum Paths {
  Example = 'example',
  LoginScreen = 'loginScreen',
  Startup = 'startup',
  ForgotPasswordScreen = 'forgotPasswordScreen',
  ChangePasswordScreen = 'changePasswordScreen',
  SignUpScreen = 'SignUpScreen',
  AdditionalInfoScreen = 'AdditionalInfoScreen',
  Onboarding = 'Onboarding',
  Onboarding2 = 'Onboarding2',
  Onboarding3 = 'Onboarding3',
  AuthStack = 'AuthStack',
  HomeStack = 'HomeStack',
  BottomTabs = 'BottomTabs',
}
